src/SosBundle/Entity/User.php
<?php

namespace SosBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity
 * @ORM\Table(name="utilisateur")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    public $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     */
    public $prenom;

    /**
     * @ORM\Column(name="information", type="string", length=255, nullable=true)
     */
    private $information;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="string", length=255)
     */
    public $telephone;

    /**
     * @var string
     *
     * @ORM\Column(name="date_naissance", type="date")
     */
    public $dateNaissance;

    /**
     *
     * @ORM\OneToMany(targetEntity="UserCritere", mappedBy="user",cascade={"remove"})
     */
    public $criteres;

    /**
     *
     * @ORM\OneToMany(targetEntity="Recommandation", mappedBy="user",cascade={"remove"})
     */
    public $recommandations;

    /**
     * @var string
     *
     * @ORM\Column(name="date_abonnement", type="datetime", nullable=true)
     */
    public $dateAbonnement;

    /**
     * @ORM\Column(name="message_5J", type="boolean", nullable=true)
     */
    private $message5J;

    /**
     * @ORM\Column(name="validation", type="boolean", nullable=true)
     */
    private $validation;

    /**
     * @var string
     *
     * @ORM\Column(name="date_inscription", type="date", nullable=true)
     */
    public $dateInscription;

    /**
     *
     * @ORM\OneToMany(targetEntity="Order", mappedBy="user",cascade={"remove"})
     */
    public $orders;


    public function setEmail($email){
        parent::setEmail($email);
        $this->setUsername($email);
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return User
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return User
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get information
     *
     * @return string
     */
    public function getInformation()
    {
        return $this->information;
    }

     /**
     * Set information
     *
     * @param string $information
     *
     * @return User
     */
    public function setInformation($information)
    {
        $this->information = $information;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     *
     * @return User
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set dateNaissance
     *
     * @param \DateTime $dateNaissance
     *
     * @return User
     */
    public function setDateNaissance($dateNaissance)
    {      
        $date = new \DateTime();
        $result = $date->createFromFormat('d/m/Y', $dateNaissance);
        $this->dateNaissance = $result;

        return $this;
    }

    /**
     * Get dateNaissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->dateNaissance;
    }

    /**
     * Set dateInscription
     *
     * @param \DateTime $dateInscription
     *
     * @return User
     */
    public function setDateInscription($dateInscription)
    {      
        $this->dateInscription = $dateInscription;
        return $this;
    }

    /**
     * Get dateInscription
     *
     * @return \DateTime
     */
    public function getDateInscription()
    {
        return $this->dateInscription;
    }

    /**
     * Set dateAbonnement
     *
     * @param \DateTime $dateAbonnement
     *
     * @return User
     */
    public function setDateAbonnement($dateAbonnement)
    {
        $this->dateAbonnement = $dateAbonnement;

        return $this;
    }

    /**
     * Get dateAbonnement
     *
     * @return \DateTime
     */
    public function getDateAbonnement()
    {
        return $this->dateAbonnement;
    }

    /**
     * Set message5J
     *
     * @param boolean $message5J
     *
     * @return User
     */
    public function setMessage5J($message5J)
    {
        $this->message5J = $message5J;

        return $this;
    }

    /**
     * Get message5J
     *
     * @return boolean
     */
    public function getMessage5J()
    {
        return $this->message5J;
    }

    /**
     * Set validation
     *
     * @param boolean $validation
     *
     * @return User
     */
    public function setValidation($validation)
    {
        $this->validation = $validation;

        return $this;
    }

    /**
     * Get validation
     *
     * @return boolean
     */
    public function getValidation()
    {
        return $this->validation;
    }

    /**
     * Add critere
     *
     * @param \SosBundle\Entity\UserCritere $critere
     *
     * @return User
     */
    public function addCritere(\SosBundle\Entity\UserCritere $critere)
    {
        $this->criteres[] = $critere;

        return $this;
    }

    /**
     * Remove critere
     *
     * @param \SosBundle\Entity\UserCritere $critere
     */
    public function removeCritere(\SosBundle\Entity\UserCritere $critere)
    {
        $this->criteres->removeElement($critere);
    }

    /**
     * Get criteres
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCriteres()
    {
        return $this->criteres;
    }
    public function getAge()
    {
        $dateInterval = $this->dateNaissance->diff(new \DateTime());
 
        return $dateInterval->y;
    }


    /**
     * Add recommandation
     *
     * @param \SosBundle\Entity\Recommandation $recommandation
     *
     * @return User
     */
    public function addRecommandation(\SosBundle\Entity\Recommandation $recommandation)
    {
        $this->recommandations[] = $recommandation;

        return $this;
    }

    /**
     * Remove recommandation
     *
     * @param \SosBundle\Entity\Recommandation $recommandation
     */
    public function removeRecommandation(\SosBundle\Entity\Recommandation $recommandation)
    {
        $this->recommandations->removeElement($recommandation);
    }

    /**
     * Get recommandations
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRecommandations()
    {
        return $this->recommandations;
    }
}

src/SosBundle/Controller/SearchController.php
<?php

namespace SosBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use SosBundle\Entity\Etablissement;
use SosBundle\Entity\Secteur;
use SosBundle\Service\Matching;
use Symfony\Component\Validator\Constraints\DateTime;

class SearchController extends Controller
{

    /**
     * @Route("/search/ville")
     */
    public function villeAction(Request $request)
    {

        return $this->render('SosBundle:Search:ville.html.twig', array('step' => '1'));

    }

    /**
     * @Route("/search/classification")
     */
    public function classificationAction(Request $request)
    {

        $data = array();
        $em = $this->getDoctrine()->getManager();

        // Validation ville
        if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "ville") {

            $alreadyVille = $request->get('ville');
            if (empty($alreadyVille['latitude'])) {
                $geocoder = 'https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyBvtLKkt2MEgUKvIat-0wBT4Hg4wQ9HkqQ&address=%s&sensor=false';
                $query = sprintf($geocoder, urlencode($_POST['ville']));
                $result = json_decode(file_get_contents($query));

                if ($result == NULL || $result == "" || $result->status == "ZERO_RESULTS" || $result->status == "INVALID_REQUEST" || $result->status == "REQUEST_DENIED") {
                    return $this->render('SosBundle:Search:ville.html.twig', array('error' => 'ville'));
                } else {
                    $json = $result->results[0];
                    $data['ville']['libelle'] = $_POST['ville'];
                    $data['ville']['latitude'] = $json->geometry->location->lat;
                    $data['ville']['longitude'] = $json->geometry->location->lng;
                }
            } else {
                $data['ville'] = $alreadyVille;
            }

            $repo = $em->getRepository("SosBundle:Etablissement");
            $etablissements = $repo->findAll();

            $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));


            return $this->render('SosBundle:Search:classification.html.twig', array('etablissements' => $etablissements, 'data' => $data, 'step' => '2'));


        } else {

            return $this->redirectToRoute($request->get('form'));

        }
    }

    //  /**
    //   * @Route("/search/secteur")
    //   */
    //  public function secteurAction(Request $request)
    //  {

    //      $data = array();
    //      $em = $this->getDoctrine()->getManager();

    //      // Validation classification
    //      if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "classification" ) {

    // $data['ville'] = $request->get('ville');
    //          $data['classification'] = $request->get('classification');

    //       $repo = $em->getRepository("SosBundle:Secteur");
    //       $secteurs = $repo->findAll();

    //       $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));

    //
    //          return $this->render('SosBundle:Search:secteur.html.twig', array('secteurs' => $secteurs, 'data' => $data, 'step' => '3'));

    //      }else{
    //          return $this->redirectToRoute($request->get('form'));
    //      }
    //  }

    //  /**
    //   * @Route("/search/service")
    //   */
    //  public function serviceAction(Request $request)
    //  {

    //      $data = array();
    //      $em = $this->getDoctrine()->getManager();

    //      // Validation secteur activité
    //      if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "secteur" ) {

    // $data['ville'] = $request->get('ville');
    //          $data['classification'] = $request->get('classification');
    //          $data['secteur_activite'] = $request->get('secteur_activite');

    //

    //          $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));

    // if ($data['secteur_activite'] == 1) {

    //  $qb = $em->createQueryBuilder();
    //  $postes = $qb->select('p')
    //             ->from('SosBundle:PosteRecherche','p')
    //             ->where('p.secteur = :secteur_activite')
    //             ->setParameter('secteur_activite', $data['secteur_activite'])
    //             ->getQuery()
    //             ->getResult();

    //  return $this->render('SosBundle:Search:poste.html.twig', array('postes' => $postes, 'data' => $data, 'step' => '5'));

    // }else if($data['secteur_activite'] == 2){

    //        $repo = $em->getRepository("SosBundle:Service");
    //        $services = $repo->findAll();

    //  return $this->render('SosBundle:Search:service.html.twig', array('services' => $services, 'data' => $data, 'step' => '4'));

    // }

    //      }else{
    //          return $this->redirectToRoute($request->get('form'));
    //      }
    //  }

    /**
     * @Route("/search/poste")
     */
    public function posteAction(Request $request)
    {

        $data = array();
        $em = $this->getDoctrine()->getManager();

        // Validation service restauration
        if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "service" || $request->get('form') == "classification") {

            $data['ville'] = $request->get('ville');
            $data['classification'] = $request->get('classification');

            $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));

            $repoPostes = $em->getRepository('SosBundle:PosteRecherche');
            $postes = $repoPostes->findBy(array(), array('id' => 'desc'));

            $repoSecteurs = $em->getRepository('SosBundle:Secteur');
            $secteurs = $repoSecteurs->findAll();

            $repoServices = $em->getRepository('SosBundle:Service');
            $services = $repoServices->findAll();



            return $this->render('SosBundle:Search:poste.html.twig', array('postes' => $postes, 'secteurs' => $secteurs, 'services' => $services, 'data' => $data, 'step' => '5'));

        } else {
            return $this->redirectToRoute($request->get('form'));
        }

    }

    /**
     * @Route("/search/contrat")
     */
    public function contratAction(Request $request)
    {

        $data = array();
        $em = $this->getDoctrine()->getManager();

        // Validation poste
        if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "poste") {

            $data['ville'] = $request->get('ville');
            $data['classification'] = $request->get('classification');
            $data['poste'] = $request->get('poste');

            $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));

            $repo = $em->getRepository("SosBundle:Contrat");
            $contrats = $repo->findBy(array(), array('id' => 'desc'));


            return $this->render('SosBundle:Search:contrat.html.twig', array('contrats' => $contrats, 'data' => $data, 'step' => '6'));

        } else {
            return $this->redirectToRoute($request->get('form'));
        }

    }

    /**
     * @Route("/search/duree")
     */
    public function dureeAction(Request $request)
    {
        $data = array();
        $em = $this->getDoctrine()->getManager();

        // Validation contrat
        if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "contrat") {

            $data['ville'] = $request->get('ville');
            $data['classification'] = $request->get('classification');
            $data['poste'] = $request->get('poste');
            $data['contrat'] = $request->get('contrat');

            $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));

            $repo = $em->getRepository("SosBundle:Contrat");
            $contrat = $repo->find($data['contrat']);


            $contrat_duree = $contrat->getDuree();
            return $this->render('SosBundle:Search:contrat_duree.html.twig', array('contrat_duree' => $contrat_duree, 'data' => $data, 'step' => '7'));

        } else {
            return $this->redirectToRoute($request->get('form'));
        }
    }

    /**
     * @Route("/search/cursus")
     */
    public function cursusAction(Request $request)
    {
        $data = array();
        $em = $this->getDoctrine()->getManager();

        // Validation contrat
        if ($request->isMethod('POST') && null !== $request->get('form') && $request->get('form') == "duree" || $request->get('form') == "contrat") {

            $data['ville'] = $request->get('ville');
            $data['classification'] = $request->get('classification');
            $data['poste'] = $request->get('poste');
            $data['contrat'] = $request->get('contrat');

            if (null !== $request->get('contrat_duree')) {
                $data['contrat_duree'] = $request->get('contrat_duree');
            }

            $data['match_employe'] = $this->get('sos.matching')->getNumberOfEmploye($data, $request->get('form'));



            $cursus_scolaire_repo = $em->getRepository("SosBundle:CursusScolaire");
            $cursus_scolaire = $cursus_scolaire_repo->findBy(array(), array('id' => 'desc'));
            return $this->render('SosBundle:Search:cursus_scolaire.html.twig', array('cursus_scolaire' => $cursus_scolaire, 'data' => $data, 'step' => '8'));
        } else {
            return $this->redirectToRoute($request->get('form'));
        }
    }

    /**
     * @Route("/search/formation")
     */
    public function formationAction(Request $request)
    {
        $data = array();

src/SosBundle/Resources/views/Search/imprimer.html.twig
<img src="https://www.soshcr.fr/img/header.png"  style="width:105%;">

<h3 style="text-align: center">Candidats répondants à vos critères de recherche :</h3>
<br><br>



<div style="
margin-left: 250px;
color: #888;
" class="col-sm-8">

	{% for employe in data.employes %}
		<div style="width: 50%;display: table;position: relative;
min-height: 1px;
padding-right: 15px;
padding-left: 15px;" class="container col-sm-6">
			<div style="margin-bottom: 20px;
background-color: #fff;
border: 1px solid transparent;
border-radius: 4px;
-webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
box-shadow: 0 1px 1px rgba(0, 0, 0, .05);" class="panel result-panel">
				<div style="padding: 10px 15px;
border-bottom: 1px solid transparent;
border-top-left-radius: 3px;
border-top-right-radius: 3px;background-color: #394076;
color: #fff;" class="panel-heading result-panel-heading">
					{{ employe.prenom ~ ' ' ~ employe.nom ~ ' (' ~ employe.age ~' ans)'}}
				</div>
				<div style="padding: 15px;" class="panel-body">
					<p>{{ employe.email }}</p>
					<p>{{ employe.telephone }}</p>
					{% if employe.nbRecommandation == 0 %}
						<p>0 recommandation</p>
					{% elseif employe.nbRecommandation  > 1 %}
						<p>{{ employe.nbRecommandation  }} recommandations</p>
					{% elseif employe.nbRecommandation  == 1 %}
						<p>{{ employe.nbRecommandation  }} recommandation</p>
					{% endif %}
				</div>

			</div>
		</div>
	{% endfor %}




</div>

src/SosBundle/Resources/views/Search/resultat.html.twig
{% extends 'SosBundle::layout.html.twig' %}

{% block sos_body %}


	<form method="post" action="{{ path('demandeCv') }}">
		<input type="hidden" name="ville[libelle]" value="{{ data.ville.libelle }}">
		<input type="hidden" name="ville[latitude]" value="{{ data.ville.latitude }}">
		<input type="hidden" name="ville[longitude]" value="{{ data.ville.longitude }}">
		<input type="hidden" name="classification" value="{{ data.classification }}">
        {% for poste in data.poste %}
			<input type="hidden" name="poste[]" value="{{ poste }}">
        {% endfor %}		<input type="hidden" name="contrat" value="{{ data.contrat }}">
		<input type="hidden" name="date_debut" value="{{ data.date_debut }}">

		{% if data.contrat_duree is defined %}
			<input type="hidden" name="contrat_duree" value="{{ data.contrat_duree }}">
		{% endif %}


		{% if data.formation_minimum is defined %}
			<input type="hidden" name="formation_minimum" value="{{ data.formation_minimum }}">
		{% endif %}


		{% if data.experience_minimum is defined %}
			<input type="hidden" name="experience_minimum" value="{{ data.experience_minimum }}">
		{% endif %}


		{% if data.cursus_scolaire is defined %}
			<input type="hidden" name="cursus_scolaire" value="{{ data.cursus_scolaire }}">
		{% endif %}




	    <div id="poste_hotellerie" class="col-xs-12 sos-form">
		<h3 class="title-heading">Voici les candidats correspondants à votre recherche :</h3>
		<br>

		<div class="col-sm-2">
		Modifier
		<div class="col-md-12">
                    <ul class="social-network social-circle">
                        <li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Classification" ><i class="" ><input name ="action" value="classification" style=" height:50px; background-image: url({{ asset('bundles/sos/global/img/rating/' ~ data.classification )}}-stars.png); color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                        <li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Poste" ><i class="" ><input name ="action" value="poste" style=" height:50px; background-image: url({{ asset('bundles/sos/global/img/poste/10.png') }}	); color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                        <br>
                        <li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Type de contrat" ><i class="" ><input name ="action" value="contrat" style=" height:50px; background-image: url({{ asset('bundles/sos/global/img/contrat/' ~ data.contrat ~ '.png') }}); color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                       	{% if data.cursus_scolaire is defined %}
                       	<li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Cursus scolaire" ><i class="" ><input name ="action" value="cursus_scolaire" style=" margin-top:6px; height:50px; background-image: url({{ asset('bundles/sos/global/img/cursus/' ~ data.cursus_scolaire  ~ '.png') }}); color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                       	{% endif %}
                       	{% if data.experience_minimum is defined %}
                       	<li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Expérience" ><i class="" ><input name ="action" value="experience_minimum" style=" height:50px; background-image: url({{ asset('bundles/sos/global/img/experience/' ~ data.experience_minimum  ~ '.png') }}); margin-top: 6px; width: 100%; color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                       	{% endif %}
                       	<br>
                       	{% if data.contrat_duree is defined %}
                       	<li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Durée du contrat" ><i class="" ><input name ="action" value="contrat_duree" style=" height:50px; background-image: url({{ asset('bundles/sos/global/img/duree_contrat/' ~ data.contrat_duree  ~ '.png') }}); width: 90%; color: transparent; float: right; border:none; background-color: transparent; background-repeat:no-repeat;background-size:contain;" class="img-responsive" type="submit" border="0"   /></i></a></li>
                       	{% endif %}


                    </ul>
        </div>
		</div>

		<div class="col-sm-8">
				tout sélectionner <input onclick="CocheTout(this, 'mail_demande_utilisateur[]');" type="checkbox">

				<br/><br>
                    {% if data.employes == null %}
                           <img style="max-width:110px" src="{{ asset('bundles/sos/global/img/loupeRes.png') }}" alt="" class="img-responsive form-img">
                           <br>
                           AUCUN CANDIDAT
                        {% endif %}

                    {% for employe in data.employes %}
					<div class="container col-sm-6">
					  <div class="panel result-panel">
					    <div class="panel-heading result-panel-heading">
							<input  style="position: absolute; left: 30px; top: 15px;" type="checkbox" value="{{employe.email}}" name="mail_demande_utilisateur[]">
							<a style="color: white;" href="{{ path('public_profil', {'id' : employe.id}) }}">{{ employe.prenom ~ ' ' ~ employe.nom ~ ' (' ~ employe.age ~' ans)'}} &nbsp &nbsp &nbsp{{'à '~ employe.distance ~' km' }} <i style="position: absolute; right: 30px; top: 15px;" class="fa fa-search" ></i></a>
						    </div>
					    <div class="panel-body">
					    	<p>{{ employe.email }}</p>
					    	<p>{{ employe.telephone }}</p>
					    </div>
					    {% if employe.getRecommandations()|length == 0 %}

                        {% elseif employe.getRecommandations()|length > 1 %}
                        	{% set nbReco = 0 %}
                        	{% for reco in employe.getRecommandations() %}
								{% if reco.valide == 2 %}
									{% set nbReco = nbReco + 1 %}
								{% endif %}
                        	{% endfor %}
                            {% if nbReco > 0 %}
								<p>
									<a href="#" class="icoTwitter" data-toggle="tooltip" title='
									{% for reco in employe.getRecommandations() %}
										{% if reco.valide == 2 %}
											{{ reco.nomEtablissement }};
										{% endif %}
									{% endfor %}'>{{ nbReco }} recommandations
									</a>
								</p>
                            {% else %}
                            	<p>0 recommandation</p>
                            {% endif %}
                        {% elseif employe.getRecommandations()|length  == 1 %}
                        	{% set nbReco = 0 %}
                        	{% for reco in employe.getRecommandations() %}
								{% if reco.valide == 2 %}
									{% set nbReco = nbReco + 1 %}
								{% endif %}
                        	{% endfor %}
                            {% if nbReco > 0 %}
								<p>
									<a href="#" class="icoTwitter" data-toggle="tooltip" title='
									{% for reco in employe.getRecommandations() %}
										{% if reco.valide == 2 %}
											{{ reco.nomEtablissement }};
										{% endif %}
									{% endfor %}' >{{ nbReco }} recommandation</a>
								</p>
                            {% else %}
                            	<p>0 recommandation</p>
                            {% endif %}

                        {% endif %}

					  </div>
					</div>
				{% endfor %}




		</div>
		<div class="col-sm-2">
		Outils
		<div class="col-md-12">
                    <ul class="social-network social-circle">
                        <li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Imprimer les resultats" ><i class="" ><input name ="action" value="imprimer" style="background-image: url({{ asset('bundles/sos/global/img/print.png') }}); color: transparent; max-width: 40px; float: right; border:none;background-color: transparent; background-repeat:no-repeat;background-size:100% 100%;" type="submit" border="0"   /></i></a></li>
                       <input type="hidden" name="form" value="resultat">
                       </form>
                        <form style="display: inline;" action="{{ path('poste')}}" method="post">
                        <input type="hidden" name="ville[libelle]" value="{{ data.ville.libelle }}">
                        <input type="hidden" name="ville[latitude]" value="{{ data.ville.latitude }}">
                        <input type="hidden" name="ville[longitude]" value="{{ data.ville.longitude }}">
                        <input type="hidden" name="classification" value="{{ data.classification }}">
                        <input type="hidden" name="form" value="classification">
                        <li><a href="#" class="icoTwitter" data-toggle="tooltip" title="Recommencer une recherche"><i class="" ><input name ="action" value=""  style="max-width: 35px; float: right; " type="image" src="{{ asset('bundles/sos/global/img/repeat.png') }}" border="0" class="img-responsive form-img" alt="Submit" /></i></a></li>
                        </form>

                    </ul>
        </div>





		</div>







   	<div class="clearfix spacer"></div>
   	{% if (js is defined) %}{{ js|raw }}{% endif %}


    <form action="{{ path('date')}}" method="post">
		<input type="hidden" name="ville[libelle]" value="{{ data.ville.libelle }}">
		<input type="hidden" name="ville[latitude]" value="{{ data.ville.latitude }}">
		<input type="hidden" name="ville[longitude]" value="{{ data.ville.longitude }}">
		<input type="hidden" name="classification" value="{{ data.classification }}">

        {% for poste in data.poste %}
			<input type="hidden" name="poste[]" value="{{ poste }}">
        {% endfor %}
		<input type="hidden" name="contrat" value="{{ data.contrat }}">

		{% if data.contrat_duree is defined %}
			<input type="hidden" name="contrat_duree" value="{{ data.contrat_duree }}">
		{% endif %}	

		{% if data.formation_minimum is defined %}
			<input type="hidden" name="formation_minimum" value="{{ data.formation_minimum }}">
		{% endif %}

		{% if data.experience_minimum is defined %}
			<input type="hidden" name="experience_minimum" value="{{ data.experience_minimum }}">
		{% endif %}

		{% if data.cursus_scolaire is defined %}
			<input type="hidden" name="cursus_scolaire" value="{{ data.cursus_scolaire }}">
		{% endif %}

		<br><br>
		<!-- <button type="submit" class="pull-left back col-sm-offset-2"><i class="fa fa-caret-left" aria-hidden="true"></i> Précédent</button> -->
	</form>
</div>

{% endblock %}